### ISSUE TITLE
<br /> doesn't show properly in heading row after MD generation

### ISSUE THREAD

**Issue by sutram** [sethyuan/logseq-plugin-luckysheet#6]
First of all, I love this plugin!

Even through `<br />` is correct markdown, it shows as is in a logseq block after exporting luckysheet to markdown.

This only happens if the table heading has `<br />` but works ok if the a normal table row has it.

Instead, if I use [:br], it works fine and a new line is correctly rendered as the heading row in the logseq table block

Thank you!

**Comment by sethyuan** [comment]
I confirmed this in Logseq 0.7.4, happens in rows too. It seems Logseq changed its behavior regarding `<br />`, I'll use `[:br]` for multi-lines as a workaround.

**Comment by sethyuan** [comment]
@sutram  New version released, please have a try.

**Comment by sutram** [comment]
> @sutram New version released, please have a try.

Thanks for fixing it so quickly @sethyuan 

Unfortunately, [:br] is still rendered as is in the header row. It works fine in a normal row. I am using Logseq 0.7.4 on Ubuntu 20.04. Please see attached screenshot
![Screenshot from 2022-06-20 22-11-59](https://user-images.githubusercontent.com/8870300/174714861-b55bd36b-28e3-472f-8e59-e6fa5a71ae4a.png)

**Comment by sutram** [comment]
I think I figured out why. It is because, the text in the header row is bolded. Without the bold markup `**` the line break renders fine. I am not sure how to solve it.

**Comment by sethyuan** [comment]
OK, since I know the root cause now, I implemented a solution for this case. I just released a new version with the fix, can you try it?

**Comment by sutram** [comment]
> OK, since I know the root cause now, I implemented a solution for this case. I just released a new version with the fix, can you try it?

Thanks @sethyuan, it works when I tried it with all bold, all italics and all strikethroughs. It doesn't work with underlines - maybe needs to be surrounded by `<u>..</u>`?

Unfortunately, I realized there are also other corner cases with mixed markup, where it still fails. Sorry, I should have thought of it earlier.

For example, first line is bold and second is italicized

![Screenshot from 2022-06-21 08-05-50](https://user-images.githubusercontent.com/8870300/174819577-419db73a-80dc-4a80-ac9b-a8c19b8f19f8.png)

First line is bold and italicized and second is normal

![Screenshot from 2022-06-21 08-07-34](https://user-images.githubusercontent.com/8870300/174819975-17870147-0cca-449f-8cd2-a5942c3d0527.png)

First line is bold and italicized and second is strikethrough

![Screenshot from 2022-06-21 08-19-54](https://user-images.githubusercontent.com/8870300/174822736-3449c702-20b7-4c2a-be0c-f2bcd3296ae6.png)

**Comment by sethyuan** [comment]
Strange, I tested these cases and they are all working fine, except underline because I didn't implement it. Can you check if you have v0.7.4 of the plugin?

**Comment by sutram** [comment]
> Strange, I tested these cases and they are all working fine, except underline because I didn't implement it. Can you check if you have v0.7.4 of the plugin?
> 
> Also, I tested underline with and discovered that Logseq does not format it well in table cells (fine in table headers?!). I'm not inclined to implement something that does not work well, so I think support for underline should wait.

I checked and I do have 0.7.4

![Screenshot from 2022-06-23 08-27-46](https://user-images.githubusercontent.com/8870300/175323798-0ce5cb61-f573-4b37-922c-90834805835d.png)

**Comment by sethyuan** [comment]
Can you make a recording of how you reproduce it? I'd like to check how you added formats in Luckysheet.

**Comment by sutram** [comment]
@sethyuan I deleted the sheet object, removed the plugin, re-installed it, created a new luckysheet object and tried again. Now, I can't reproduce my issue anymore. It seems like the old code was still being used even after upgrading to LuckySheet 0.7.4. 

At this point, the issue can be closed. Thanks for following up.

**Comment by sethyuan** [comment]
Great!
